services:
  - type: web
    name: animebotsu
    env: python
    plan: free
    buildCommand: ""
    startCommand: python bot.py
    runtime: python3.11
    envVars:
      - key: TOKEN
        value: 8087642219:AAEp-vuWjecCWxjcOMQUGWQjXbcZuKGCwWU